export const STORAGE_CHAT_CUSTOMER_ID = 'STORAGE_CHAT_CUSTOMER_ID';
export const STORAGE_CHAT_CUSTOMER_NAME = 'STORAGE_CHAT_CUSTOMER_NAME';
export const STORAGE_CHAT_THREAD_ID = 'STORAGE_CHAT_THREAD_ID';
export const STORAGE_CHAT_AUTHORIZATION_CODE =
  'STORAGE_CHAT_AUTHORIZATION_CODE';
